
[tool.towncrier]
package = "lsst.ts.xml"
package_dir = "python"
filename = "doc/version-history.rst"
directory = "doc/news"
filename_format = "{name}.{type}.rst|{name}.{type}.md"
title_format = "{version} ({project_date})"
issue_format = "`{issue} <https://rubinobs.atlassian.net/browse/{issue}>`_"

[[tool.towncrier.section]]
name = "Package Level"
path = ""

[[tool.towncrier.section]]
name = "Interface Changes"
path = "interface_changes"

[[tool.towncrier.type]]
directory = "feature"
name = "New Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "perf"
name = "Performance Enhancement"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "API Removal or Deprecation"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Other Changes and Additions"
showcontent = true

[[tool.towncrier.type]]
directory = "ataos"
name = "ATAOS"
showcontent = true


[[tool.towncrier.type]]
directory = "atbuilding"
name = "ATBuilding"
showcontent = true

[[tool.towncrier.type]]
directory = "atcamera"
name = "ATCamera"
showcontent = true

[[tool.towncrier.type]]
directory = "atdome"
name = "ATDome"
showcontent = true

[[tool.towncrier.type]]
directory = "atdometrajectory"
name = "ATDomeTrajectory"
showcontent = true

[[tool.towncrier.type]]
directory = "atheaderservice"
name = "ATHeaderService"
showcontent = true

[[tool.towncrier.type]]
directory = "athexapod"
name = "ATHexapod"
showcontent = true

[[tool.towncrier.type]]
directory = "atmcs"
name = "ATMCS"
showcontent = true

[[tool.towncrier.type]]
directory = "atmonochromator"
name = "ATMonochromator"
showcontent = true

[[tool.towncrier.type]]
directory = "atoods"
name = "ATOODS"
showcontent = true

[[tool.towncrier.type]]
directory = "atpneumatics"
name = "ATPneumatics"
showcontent = true

[[tool.towncrier.type]]
directory = "atptg"
name = "ATPtg"
showcontent = true

[[tool.towncrier.type]]
directory = "atspectrograph"
name = "ATSpectrograph"
showcontent = true

[[tool.towncrier.type]]
directory = "atwhitelight"
name = "ATWhiteLight"
showcontent = true

[[tool.towncrier.type]]
directory = "authorize"
name = "Authorize"
showcontent = true

[[tool.towncrier.type]]
directory = "cbp"
name = "CBP"
showcontent = true

[[tool.towncrier.type]]
directory = "cccamera"
name = "CCCamera"
showcontent = true

[[tool.towncrier.type]]
directory = "ccheaderservice"
name = "CCHeaderService"
showcontent = true

[[tool.towncrier.type]]
directory = "ccoods"
name = "CCOODS"
showcontent = true

[[tool.towncrier.type]]
directory = "dimm"
name = "DIMM"
showcontent = true

[[tool.towncrier.type]]
directory = "dream"
name = "DREAM"
showcontent = true

[[tool.towncrier.type]]
directory = "dsm"
name = "DSM"
showcontent = true

[[tool.towncrier.type]]
directory = "eas"
name = "EAS"
showcontent = true

[[tool.towncrier.type]]
directory = "epm"
name = "EPM"
showcontent = true

[[tool.towncrier.type]]
directory = "ess"
name = "ESS"
showcontent = true

[[tool.towncrier.type]]
directory = "electrometer"
name = "Electrometer"
showcontent = true

[[tool.towncrier.type]]
directory = "fiberspectrograph"
name = "FiberSpectrograph"
showcontent = true

[[tool.towncrier.type]]
directory = "gcheaderservice"
name = "GCHeaderService"
showcontent = true

[[tool.towncrier.type]]
directory = "gis"
name = "GIS"
showcontent = true

[[tool.towncrier.type]]
directory = "genericcamera"
name = "GenericCamera"
showcontent = true

[[tool.towncrier.type]]
directory = "guider"
name = "Guider"
showcontent = true

[[tool.towncrier.type]]
directory = "hvac"
name = "HVAC"
showcontent = true

[[tool.towncrier.type]]
directory = "ledprojector"
name = "LEDProjector"
showcontent = true

[[tool.towncrier.type]]
directory = "love"
name = "LOVE"
showcontent = true

[[tool.towncrier.type]]
directory = "lasertracker"
name = "LaserTracker"
showcontent = true

[[tool.towncrier.type]]
directory = "linearstage"
name = "LinearStage"
showcontent = true

[[tool.towncrier.type]]
directory = "mtaos"
name = "MTAOS"
showcontent = true

[[tool.towncrier.type]]
directory = "mtaircompressor"
name = "MTAirCompressor"
showcontent = true

[[tool.towncrier.type]]
directory = "mtcamera"
name = "MTCamera"
showcontent = true

[[tool.towncrier.type]]
directory = "mtdome"
name = "MTDome"
showcontent = true

[[tool.towncrier.type]]
directory = "mtdometrajectory"
name = "MTDomeTrajectory"
showcontent = true

[[tool.towncrier.type]]
directory = "mteec"
name = "MTEEC"
showcontent = true

[[tool.towncrier.type]]
directory = "mtheaderservice"
name = "MTHeaderService"
showcontent = true

[[tool.towncrier.type]]
directory = "mthexapod"
name = "MTHexapod"
showcontent = true

[[tool.towncrier.type]]
directory = "mtm1m3"
name = "MTM1M3"
showcontent = true

[[tool.towncrier.type]]
directory = "mtm1m3ts"
name = "MTM1M3TS"
showcontent = true

[[tool.towncrier.type]]
directory = "mtm2"
name = "MTM2"
showcontent = true

[[tool.towncrier.type]]
directory = "mtmount"
name = "MTMount"
showcontent = true

[[tool.towncrier.type]]
directory = "mtoods"
name = "MTOODS"
showcontent = true

[[tool.towncrier.type]]
directory = "mtptg"
name = "MTPtg"
showcontent = true

[[tool.towncrier.type]]
directory = "mtrotator"
name = "MTRotator"
showcontent = true

[[tool.towncrier.type]]
directory = "mtvms"
name = "MTVMS"
showcontent = true

[[tool.towncrier.type]]
directory = "ocps"
name = "OCPS"
showcontent = true

[[tool.towncrier.type]]
directory = "pmd"
name = "PMD"
showcontent = true

[[tool.towncrier.type]]
directory = "mtreflector"
name = "MTReflector"
showcontent = true

[[tool.towncrier.type]]
directory = "scheduler"
name = "Scheduler"
showcontent = true

[[tool.towncrier.type]]
directory = "script"
name = "Script"
showcontent = true

[[tool.towncrier.type]]
directory = "scriptqueue"
name = "ScriptQueue"
showcontent = true

[[tool.towncrier.type]]
directory = "summitfacility"
name = "SummitFacility"
showcontent = true

[[tool.towncrier.type]]
directory = "test"
name = "Test"
showcontent = true

[[tool.towncrier.type]]
directory = "tunablelaser"
name = "TunableLaser"
showcontent = true

[[tool.towncrier.type]]
directory = "watcher"
name = "Watcher"
showcontent = true

[[tool.towncrier.type]]
directory = "weatherforecast"
name = "WeatherForecast"
showcontent = true
