name: CI

on: [push, pull_request]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -e .[dev]
          python -m pip install -e .[test]
          python -m pip install ltd-conveyor
          python -m pip install sphinxext-rediraffe
          python -m pip install myst_nb
      - name: Build documentation
        run: |
          cd doc
          make html

      - name: Upload to LSST the Docs
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        run: ltd upload --product ts-xml --gh --dir doc/_build/html
