name: CI

on: push

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -e .[dev,test]
          python -m pip install ltd-conveyor
      - name: Build documentation
        run: |
          cd doc
          make html

      - name: Upload to LSST the Docs
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        run: ltd upload --product ts-xml --gh --dir doc/_build/html
