name: test-xmllint-format

on: [push]

jobs:
  xmllint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: lsst-ts/xmllint-format-lint-action@v0.1
      with:
        source: './sal_interfaces'
        extensions: 'xml'
